#!/usr/bin/python
# -*- coding:  utf-8 -*-
# Parametrisation file of WASP-76
import numpy as np

# Parameters

# instruments


# instruments LC
LC = {'CHEOPS': {'Dataset': {0: 'instPC0',
                             1: 'instPC1',
                             2: 'instPC2',
                             10: 'instTr0',
                             11: 'instTr1',
                             12: 'instTr2',
                             13: 'instTr3',
                             14: 'instTr4',
                             15: 'instTr5',
                             100: 'inst0',
                             101: 'inst1',
                             102: 'inst2',
                             103: 'inst3',
                             104: 'inst4',
                             105: 'inst5',
                             106: 'inst6',
                             107: 'inst7',
                             108: 'inst8',
                             109: 'inst9',
                             110: 'inst10',
                             111: 'inst11',
                             112: 'inst12',
                             113: 'inst13',
                             114: 'inst14',
                             115: 'inst15',
                             116: 'inst16',
                             117: 'inst17',
                             118: 'inst18',
                             119: 'inst19'},
                 'inst0': {'DeltaF': {'duplicate': None,
                                      'free': True,
                                      'prior': {'args': {'mu': 0.0284, 'sigma': np.sqrt(0.001**2 + 0.00030**2)},  # From TS3 Tom Wilson and script_prior
                                                'category': 'normal',
                                                'joint_prior_ref': None},
                                      'unit': 'wo unit',
                                      'value': None},
                           'contam': {'duplicate': None,
                                      'free': True,
                                      'prior': {'args': {'mu': 0.0284, 'sigma': 0.001},  # From TS3 Tom Wilson
                                                'category': 'normal',
                                                'joint_prior_ref': None},
                                      'unit': 'wo unit',
                                      'value': None},
                           'jitter': {'duplicate': None,
                                      'free': True,
                                      'prior': {'args': {'vmax': 0.0012, 'vmin': 0.0},
                                                'category': 'uniform',
                                                'joint_prior_ref': None},
                                      'unit': None,
                                      'value': None}},
                 'inst1': {'DeltaF': {'duplicate': None,
                                      'free': True,
                                      'prior': {'args': {'mu': 0.0284, 'sigma': np.sqrt(0.001**2 + 0.00068**2)},  # From TS3 Tom Wilson and script_prior
                                                'category': 'normal',
                                                'joint_prior_ref': None},
                                      'unit': 'wo unit',
                                      'value': None},
                           'contam': {'duplicate': 'LC_CHEOPS_inst0_contam',
                                      'free': False,
                                      'prior': {'args': {'vmax': 1.0, 'vmin': 0.0},
                                                'category': 'uniform',
                                                'joint_prior_ref': None},
                                      'unit': 'wo unit',
                                      'value': 0},
                           'jitter': {'duplicate': 'LC_CHEOPS_inst0_jitter',
                                      'free': True,
                                      'prior': {'args': {'vmax': 1.0, 'vmin': 0.0},
                                                'category': 'uniform',
                                                'joint_prior_ref': None},
                                      'unit': None,
                                      'value': None}},
                 'inst2': {'DeltaF': {'duplicate': None,
                                      'free': True,
                                      'prior': {'args': {'mu': 0.0284, 'sigma': np.sqrt(0.001**2 + 0.00043**2)},  # From TS3 Tom Wilson and script_prior
                                                'category': 'normal',
                                                'joint_prior_ref': None},
                                      'unit': 'wo unit',
                                      'value': None},
                           'contam': {'duplicate': 'LC_CHEOPS_inst0_contam',
                                      'free': False,
                                      'prior': {'args': {'vmax': 1.0, 'vmin': 0.0},
                                                'category': 'uniform',
                                                'joint_prior_ref': None},
                                      'unit': 'wo unit',
                                      'value': 0},
                           'jitter': {'duplicate': 'LC_CHEOPS_inst0_jitter',
                                      'free': True,
                                      'prior': {'args': {'vmax': 1.0, 'vmin': 0.0},
                                                'category': 'uniform',
                                                'joint_prior_ref': None},
                                      'unit': None,
                                      'value': None}},
                 'inst3': {'DeltaF': {'duplicate': None,
                                      'free': True,
                                      'prior': {'args': {'mu': 0.0284, 'sigma': np.sqrt(0.001**2 + 0.00034**2)},  # From TS3 Tom Wilson and script_prior
                                                'category': 'normal',
                                                'joint_prior_ref': None},
                                      'unit': 'wo unit',
                                      'value': None},
                           'contam': {'duplicate': 'LC_CHEOPS_inst0_contam',
                                      'free': False,
                                      'prior': {'args': {'vmax': 1.0, 'vmin': 0.0},
                                                'category': 'uniform',
                                                'joint_prior_ref': None},
                                      'unit': 'wo unit',
                                      'value': 0},
                           'jitter': {'duplicate': 'LC_CHEOPS_inst0_jitter',
                                      'free': True,
                                      'prior': {'args': {'vmax': 1.0, 'vmin': 0.0},
                                                'category': 'uniform',
                                                'joint_prior_ref': None},
                                      'unit': None,
                                      'value': None}},
                 'inst4': {'DeltaF': {'duplicate': None,
                                      'free': True,
                                      'prior': {'args': {'mu': 0.0284, 'sigma': np.sqrt(0.001**2 + 0.00046**2)},  # From TS3 Tom Wilson and script_prior
                                                'category': 'normal',
                                                'joint_prior_ref': None},
                                      'unit': 'wo unit',
                                      'value': None},
                           'contam': {'duplicate': 'LC_CHEOPS_inst0_contam',
                                      'free': False,
                                      'prior': {'args': {'vmax': 1.0, 'vmin': 0.0},
                                                'category': 'uniform',
                                                'joint_prior_ref': None},
                                      'unit': 'wo unit',
                                      'value': 0},
                           'jitter': {'duplicate': 'LC_CHEOPS_inst0_jitter',
                                      'free': True,
                                      'prior': {'args': {'vmax': 1.0, 'vmin': 0.0},
                                                'category': 'uniform',
                                                'joint_prior_ref': None},
                                      'unit': None,
                                      'value': None}},
                 'inst5': {'DeltaF': {'duplicate': None,
                                      'free': True,
                                      'prior': {'args': {'mu': 0.0284, 'sigma': np.sqrt(0.001**2 + 0.00048**2)},  # From TS3 Tom Wilson and script_prior
                                                'category': 'normal',
                                                'joint_prior_ref': None},
                                      'unit': 'wo unit',
                                      'value': None},
                           'contam': {'duplicate': 'LC_CHEOPS_inst0_contam',
                                      'free': False,
                                      'prior': {'args': {'vmax': 1.0, 'vmin': 0.0},
                                                'category': 'uniform',
                                                'joint_prior_ref': None},
                                      'unit': 'wo unit',
                                      'value': 0},
                           'jitter': {'duplicate': 'LC_CHEOPS_inst0_jitter',
                                      'free': True,
                                      'prior': {'args': {'vmax': 1.0, 'vmin': 0.0},
                                                'category': 'uniform',
                                                'joint_prior_ref': None},
                                      'unit': None,
                                      'value': None}},
                 'inst6': {'DeltaF': {'duplicate': None,
                                      'free': True,
                                      'prior': {'args': {'mu': 0.0284, 'sigma': np.sqrt(0.001**2 + 0.00042**2)},  # From TS3 Tom Wilson and script_prior
                                                'category': 'normal',
                                                'joint_prior_ref': None},
                                      'unit': 'wo unit',
                                      'value': None},
                           'contam': {'duplicate': 'LC_CHEOPS_inst0_contam',
                                      'free': False,
                                      'prior': {'args': {'vmax': 1.0, 'vmin': 0.0},
                                                'category': 'uniform',
                                                'joint_prior_ref': None},
                                      'unit': 'wo unit',
                                      'value': 0},
                           'jitter': {'duplicate': 'LC_CHEOPS_inst0_jitter',
                                      'free': True,
                                      'prior': {'args': {'vmax': 1.0, 'vmin': 0.0},
                                                'category': 'uniform',
                                                'joint_prior_ref': None},
                                      'unit': None,
                                      'value': None}},
                 'inst7': {'DeltaF': {'duplicate': None,
                                      'free': True,
                                      'prior': {'args': {'mu': 0.0284, 'sigma': np.sqrt(0.001**2 + 0.00031**2)},  # From TS3 Tom Wilson and script_prior
                                                'category': 'normal',
                                                'joint_prior_ref': None},
                                      'unit': 'wo unit',
                                      'value': None},
                           'contam': {'duplicate': 'LC_CHEOPS_inst0_contam',
                                      'free': False,
                                      'prior': {'args': {'vmax': 1.0, 'vmin': 0.0},
                                                'category': 'uniform',
                                                'joint_prior_ref': None},
                                      'unit': 'wo unit',
                                      'value': 0},
                           'jitter': {'duplicate': 'LC_CHEOPS_inst0_jitter',
                                      'free': True,
                                      'prior': {'args': {'vmax': 1.0, 'vmin': 0.0},
                                                'category': 'uniform',
                                                'joint_prior_ref': None},
                                      'unit': None,
                                      'value': None}},
                 'inst8': {'DeltaF': {'duplicate': None,
                                      'free': True,
                                      'prior': {'args': {'mu': 0.0284, 'sigma': np.sqrt(0.001**2 + 0.00041**2)},  # From TS3 Tom Wilson and script_prior
                                                'category': 'normal',
                                                'joint_prior_ref': None},
                                      'unit': 'wo unit',
                                      'value': None},
                           'contam': {'duplicate': 'LC_CHEOPS_inst0_contam',
                                      'free': False,
                                      'prior': {'args': {'vmax': 1.0, 'vmin': 0.0},
                                                'category': 'uniform',
                                                'joint_prior_ref': None},
                                      'unit': 'wo unit',
                                      'value': 0},
                           'jitter': {'duplicate': 'LC_CHEOPS_inst0_jitter',
                                      'free': True,
                                      'prior': {'args': {'vmax': 1.0, 'vmin': 0.0},
                                                'category': 'uniform',
                                                'joint_prior_ref': None},
                                      'unit': None,
                                      'value': None}},
                 'inst9': {'DeltaF': {'duplicate': None,
                                      'free': True,
                                      'prior': {'args': {'mu': 0.0284, 'sigma': np.sqrt(0.001**2 + 0.0004**2)},  # From TS3 Tom Wilson and script_prior
                                                'category': 'normal',
                                                'joint_prior_ref': None},
                                      'unit': 'wo unit',
                                      'value': None},
                           'contam': {'duplicate': 'LC_CHEOPS_inst0_contam',
                                      'free': False,
                                      'prior': {'args': {'vmax': 1.0, 'vmin': 0.0},
                                                'category': 'uniform',
                                                'joint_prior_ref': None},
                                      'unit': 'wo unit',
                                      'value': 0},
                           'jitter': {'duplicate': 'LC_CHEOPS_inst0_jitter',
                                      'free': True,
                                      'prior': {'args': {'vmax': 1.0, 'vmin': 0.0},
                                                'category': 'uniform',
                                                'joint_prior_ref': None},
                                      'unit': None,
                                      'value': None}},
                 'inst10': {'DeltaF': {'duplicate': None,
                                       'free': True,
                                       'prior': {'args': {'mu': 0.0284, 'sigma': np.sqrt(0.001**2 + 0.00043**2)},  # From TS3 Tom Wilson and script_prior
                                                 'category': 'normal',
                                                 'joint_prior_ref': None},
                                       'unit': 'wo unit',
                                       'value': None},
                            'contam': {'duplicate': 'LC_CHEOPS_inst0_contam',
                                       'free': False,
                                       'prior': {'args': {'vmax': 1.0, 'vmin': 0.0},
                                                 'category': 'uniform',
                                                 'joint_prior_ref': None},
                                       'unit': 'wo unit',
                                       'value': 0},
                            'jitter': {'duplicate': 'LC_CHEOPS_inst0_jitter',
                                       'free': True,
                                       'prior': {'args': {'vmax': 1.0, 'vmin': 0.0},
                                                 'category': 'uniform',
                                                 'joint_prior_ref': None},
                                       'unit': None,
                                       'value': None}},
                 'inst11': {'DeltaF': {'duplicate': None,
                                       'free': True,
                                       'prior': {'args': {'mu': 0.0284, 'sigma': np.sqrt(0.001**2 + 0.00032**2)},  # From TS3 Tom Wilson and script_prior
                                                 'category': 'normal',
                                                 'joint_prior_ref': None},
                                       'unit': 'wo unit',
                                       'value': None},
                            'contam': {'duplicate': 'LC_CHEOPS_inst0_contam',
                                       'free': False,
                                       'prior': {'args': {'vmax': 1.0, 'vmin': 0.0},
                                                 'category': 'uniform',
                                                 'joint_prior_ref': None},
                                       'unit': 'wo unit',
                                       'value': 0},
                            'jitter': {'duplicate': 'LC_CHEOPS_inst0_jitter',
                                       'free': True,
                                       'prior': {'args': {'vmax': 1.0, 'vmin': 0.0},
                                                 'category': 'uniform',
                                                 'joint_prior_ref': None},
                                       'unit': None,
                                       'value': None}},
                 'inst12': {'DeltaF': {'duplicate': None,
                                       'free': True,
                                       'prior': {'args': {'mu': 0.0284, 'sigma': np.sqrt(0.001**2 + 0.00029**2)},  # From TS3 Tom Wilson and script_prior
                                                 'category': 'normal',
                                                 'joint_prior_ref': None},
                                       'unit': 'wo unit',
                                       'value': None},
                            'contam': {'duplicate': 'LC_CHEOPS_inst0_contam',
                                       'free': False,
                                       'prior': {'args': {'vmax': 1.0, 'vmin': 0.0},
                                                 'category': 'uniform',
                                                 'joint_prior_ref': None},
                                       'unit': 'wo unit',
                                       'value': 0},
                            'jitter': {'duplicate': 'LC_CHEOPS_inst0_jitter',
                                       'free': True,
                                       'prior': {'args': {'vmax': 1.0, 'vmin': 0.0},
                                                 'category': 'uniform',
                                                 'joint_prior_ref': None},
                                       'unit': None,
                                       'value': None}},
                 'inst13': {'DeltaF': {'duplicate': None,
                                       'free': True,
                                       'prior': {'args': {'mu': 0.0284, 'sigma': np.sqrt(0.001**2 + 0.00042**2)},  # From TS3 Tom Wilson and script_prior
                                                 'category': 'normal',
                                                 'joint_prior_ref': None},
                                       'unit': 'wo unit',
                                       'value': None},
                            'contam': {'duplicate': 'LC_CHEOPS_inst0_contam',
                                       'free': False,
                                       'prior': {'args': {'vmax': 1.0, 'vmin': 0.0},
                                                 'category': 'uniform',
                                                 'joint_prior_ref': None},
                                       'unit': 'wo unit',
                                       'value': 0},
                            'jitter': {'duplicate': 'LC_CHEOPS_inst0_jitter',
                                       'free': True,
                                       'prior': {'args': {'vmax': 1.0, 'vmin': 0.0},
                                                 'category': 'uniform',
                                                 'joint_prior_ref': None},
                                       'unit': None,
                                       'value': None}},
                 'inst14': {'DeltaF': {'duplicate': None,
                                       'free': True,
                                       'prior': {'args': {'mu': 0.0284, 'sigma': np.sqrt(0.001**2 + 0.00031**2)},  # From TS3 Tom Wilson and script_prior
                                                 'category': 'normal',
                                                 'joint_prior_ref': None},
                                       'unit': 'wo unit',
                                       'value': None},
                            'contam': {'duplicate': 'LC_CHEOPS_inst0_contam',
                                       'free': False,
                                       'prior': {'args': {'vmax': 1.0, 'vmin': 0.0},
                                                 'category': 'uniform',
                                                 'joint_prior_ref': None},
                                       'unit': 'wo unit',
                                       'value': 0},
                            'jitter': {'duplicate': 'LC_CHEOPS_inst0_jitter',
                                       'free': True,
                                       'prior': {'args': {'vmax': 1.0, 'vmin': 0.0},
                                                 'category': 'uniform',
                                                 'joint_prior_ref': None},
                                       'unit': None,
                                       'value': None}},
                 'inst15': {'DeltaF': {'duplicate': None,
                                       'free': True,
                                       'prior': {'args': {'mu': 0.0284, 'sigma': np.sqrt(0.001**2 + 0.00041**2)},  # From TS3 Tom Wilson and script_prior
                                                 'category': 'normal',
                                                 'joint_prior_ref': None},
                                       'unit': 'wo unit',
                                       'value': None},
                            'contam': {'duplicate': 'LC_CHEOPS_inst0_contam',
                                       'free': False,
                                       'prior': {'args': {'vmax': 1.0, 'vmin': 0.0},
                                                 'category': 'uniform',
                                                 'joint_prior_ref': None},
                                       'unit': 'wo unit',
                                       'value': 0},
                            'jitter': {'duplicate': 'LC_CHEOPS_inst0_jitter',
                                       'free': True,
                                       'prior': {'args': {'vmax': 1.0, 'vmin': 0.0},
                                                 'category': 'uniform',
                                                 'joint_prior_ref': None},
                                       'unit': None,
                                       'value': None}},
                 'inst16': {'DeltaF': {'duplicate': None,
                                       'free': True,
                                       'prior': {'args': {'mu': 0.0284, 'sigma': np.sqrt(0.001**2 + 0.00032**2)},  # From TS3 Tom Wilson and script_prior
                                                 'category': 'normal',
                                                 'joint_prior_ref': None},
                                       'unit': 'wo unit',
                                       'value': None},
                            'contam': {'duplicate': 'LC_CHEOPS_inst0_contam',
                                       'free': False,
                                       'prior': {'args': {'vmax': 1.0, 'vmin': 0.0},
                                                 'category': 'uniform',
                                                 'joint_prior_ref': None},
                                       'unit': 'wo unit',
                                       'value': 0},
                            'jitter': {'duplicate': 'LC_CHEOPS_inst0_jitter',
                                       'free': True,
                                       'prior': {'args': {'vmax': 1.0, 'vmin': 0.0},
                                                 'category': 'uniform',
                                                 'joint_prior_ref': None},
                                       'unit': None,
                                       'value': None}},
                 'inst17': {'DeltaF': {'duplicate': None,
                                       'free': True,
                                       'prior': {'args': {'mu': 0.0284, 'sigma': np.sqrt(0.001**2 + 0.00031**2)},  # From TS3 Tom Wilson and script_prior
                                                 'category': 'normal',
                                                 'joint_prior_ref': None},
                                       'unit': 'wo unit',
                                       'value': None},
                            'contam': {'duplicate': 'LC_CHEOPS_inst0_contam',
                                       'free': False,
                                       'prior': {'args': {'vmax': 1.0, 'vmin': 0.0},
                                                 'category': 'uniform',
                                                 'joint_prior_ref': None},
                                       'unit': 'wo unit',
                                       'value': 0},
                            'jitter': {'duplicate': 'LC_CHEOPS_inst0_jitter',
                                       'free': True,
                                       'prior': {'args': {'vmax': 1.0, 'vmin': 0.0},
                                                 'category': 'uniform',
                                                 'joint_prior_ref': None},
                                       'unit': None,
                                       'value': None}},
                 'inst18': {'DeltaF': {'duplicate': None,
                                       'free': True,
                                       'prior': {'args': {'mu': 0.0284, 'sigma': np.sqrt(0.001**2 + 0.00031**2)},  # From TS3 Tom Wilson and script_prior
                                                 'category': 'normal',
                                                 'joint_prior_ref': None},
                                       'unit': 'wo unit',
                                       'value': None},
                            'contam': {'duplicate': 'LC_CHEOPS_inst0_contam',
                                       'free': False,
                                       'prior': {'args': {'vmax': 1.0, 'vmin': 0.0},
                                                 'category': 'uniform',
                                                 'joint_prior_ref': None},
                                       'unit': 'wo unit',
                                       'value': 0},
                            'jitter': {'duplicate': 'LC_CHEOPS_inst0_jitter',
                                       'free': True,
                                       'prior': {'args': {'vmax': 1.0, 'vmin': 0.0},
                                                 'category': 'uniform',
                                                 'joint_prior_ref': None},
                                       'unit': None,
                                       'value': None}},
                 'inst19': {'DeltaF': {'duplicate': None,
                                       'free': True,
                                       'prior': {'args': {'mu': 0.0284, 'sigma': np.sqrt(0.001**2 + 0.00032**2)},  # From TS3 Tom Wilson and script_prior
                                                 'category': 'normal',
                                                 'joint_prior_ref': None},
                                       'unit': 'wo unit',
                                       'value': None},
                            'contam': {'duplicate': 'LC_CHEOPS_inst0_contam',
                                       'free': False,
                                       'prior': {'args': {'vmax': 1.0, 'vmin': 0.0},
                                                 'category': 'uniform',
                                                 'joint_prior_ref': None},
                                       'unit': 'wo unit',
                                       'value': 0},
                            'jitter': {'duplicate': 'LC_CHEOPS_inst0_jitter',
                                       'free': True,
                                       'prior': {'args': {'vmax': 1.0, 'vmin': 0.0},
                                                 'category': 'uniform',
                                                 'joint_prior_ref': None},
                                       'unit': None,
                                       'value': None}},
                 'instPC0': {'DeltaF': {'duplicate': None,
                                        'free': True,
                                        'prior': {'args': {'mu': 0.0284, 'sigma': np.sqrt(0.001**2 + 0.0039**2)},  # From TS3 Tom Wilson and script_prior
                                                  'category': 'normal',
                                                  'joint_prior_ref': None},
                                        'unit': 'wo unit',
                                        'value': None},
                             'contam': {'duplicate': 'LC_CHEOPS_inst0_contam',
                                        'free': False,
                                        'prior': {'args': {'vmax': 1.0, 'vmin': 0.0},
                                                  'category': 'uniform',
                                                  'joint_prior_ref': None},
                                        'unit': 'wo unit',
                                        'value': 0},
                             'jitter': {'duplicate': 'LC_CHEOPS_inst0_jitter',
                                        'free': True,
                                        'prior': {'args': {'vmax': 1.0, 'vmin': 0.0},
                                                  'category': 'uniform',
                                                  'joint_prior_ref': None},
                                        'unit': None,
                                        'value': None}},
                 'instPC1': {'DeltaF': {'duplicate': None,
                                        'free': True,
                                        'prior': {'args': {'mu': 0.0284, 'sigma': np.sqrt(0.001**2 + 0.0033**2)},  # From TS3 Tom Wilson and script_prior
                                                  'category': 'normal',
                                                  'joint_prior_ref': None},
                                        'unit': 'wo unit',
                                        'value': None},
                             'contam': {'duplicate': 'LC_CHEOPS_inst0_contam',
                                        'free': False,
                                        'prior': {'args': {'vmax': 1.0, 'vmin': 0.0},
                                                  'category': 'uniform',
                                                  'joint_prior_ref': None},
                                        'unit': 'wo unit',
                                        'value': 0},
                             'jitter': {'duplicate': 'LC_CHEOPS_inst0_jitter',
                                        'free': True,
                                        'prior': {'args': {'vmax': 1.0, 'vmin': 0.0},
                                                  'category': 'uniform',
                                                  'joint_prior_ref': None},
                                        'unit': None,
                                        'value': None}},
                 'instPC2': {'DeltaF': {'duplicate': None,
                                        'free': True,
                                        'prior': {'args': {'mu': 0.0284, 'sigma': np.sqrt(0.001**2 + 0.0028**2)},  # From TS3 Tom Wilson and script_prior
                                                  'category': 'normal',
                                                  'joint_prior_ref': None},
                                        'unit': 'wo unit',
                                        'value': None},
                             'contam': {'duplicate': 'LC_CHEOPS_inst0_contam',
                                        'free': False,
                                        'prior': {'args': {'vmax': 1.0, 'vmin': 0.0},
                                                  'category': 'uniform',
                                                  'joint_prior_ref': None},
                                        'unit': 'wo unit',
                                        'value': 0},
                             'jitter': {'duplicate': 'LC_CHEOPS_inst0_jitter',
                                        'free': True,
                                        'prior': {'args': {'vmax': 1.0, 'vmin': 0.0},
                                                  'category': 'uniform',
                                                  'joint_prior_ref': None},
                                        'unit': None,
                                        'value': None}},
                 'instTr0': {'DeltaF': {'duplicate': None,
                                        'free': True,
                                        'prior': {'args': {'mu': 0.0284, 'sigma': np.sqrt(0.001**2 + 0.0058**2)},  # From TS3 Tom Wilson and script_prior
                                                  'category': 'normal',
                                                  'joint_prior_ref': None},
                                        'unit': 'wo unit',
                                        'value': None},
                             'contam': {'duplicate': 'LC_CHEOPS_inst0_contam',
                                        'free': False,
                                        'prior': {'args': {'vmax': 1.0, 'vmin': 0.0},
                                                  'category': 'uniform',
                                                  'joint_prior_ref': None},
                                        'unit': 'wo unit',
                                        'value': 0},
                             'jitter': {'duplicate': 'LC_CHEOPS_inst0_jitter',
                                        'free': True,
                                        'prior': {'args': {'vmax': 1.0, 'vmin': 0.0},
                                                  'category': 'uniform',
                                                  'joint_prior_ref': None},
                                        'unit': None,
                                        'value': None}},
                 'instTr1': {'DeltaF': {'duplicate': None,
                                        'free': True,
                                        'prior': {'args': {'mu': 0.0284, 'sigma': np.sqrt(0.001**2 + 0.0061**2)},  # From TS3 Tom Wilson and script_prior
                                                  'category': 'normal',
                                                  'joint_prior_ref': None},
                                        'unit': 'wo unit',
                                        'value': None},
                             'contam': {'duplicate': 'LC_CHEOPS_inst0_contam',
                                        'free': False,
                                        'prior': {'args': {'vmax': 1.0, 'vmin': 0.0},
                                                  'category': 'uniform',
                                                  'joint_prior_ref': None},
                                        'unit': 'wo unit',
                                        'value': 0},
                             'jitter': {'duplicate': 'LC_CHEOPS_inst0_jitter',
                                        'free': True,
                                        'prior': {'args': {'vmax': 1.0, 'vmin': 0.0},
                                                  'category': 'uniform',
                                                  'joint_prior_ref': None},
                                        'unit': None,
                                        'value': None}},
                 'instTr2': {'DeltaF': {'duplicate': None,
                                        'free': True,
                                        'prior': {'args': {'mu': 0.0284, 'sigma': np.sqrt(0.001**2 + 0.0056**2)},  # From TS3 Tom Wilson and script_prior
                                                  'category': 'normal',
                                                  'joint_prior_ref': None},
                                        'unit': 'wo unit',
                                        'value': None},
                             'contam': {'duplicate': 'LC_CHEOPS_inst0_contam',
                                        'free': False,
                                        'prior': {'args': {'vmax': 1.0, 'vmin': 0.0},
                                                  'category': 'uniform',
                                                  'joint_prior_ref': None},
                                        'unit': 'wo unit',
                                        'value': 0},
                             'jitter': {'duplicate': 'LC_CHEOPS_inst0_jitter',
                                        'free': True,
                                        'prior': {'args': {'vmax': 1.0, 'vmin': 0.0},
                                                  'category': 'uniform',
                                                  'joint_prior_ref': None},
                                        'unit': None,
                                        'value': None}},
                 'instTr3': {'DeltaF': {'duplicate': None,
                                        'free': True,
                                        'prior': {'args': {'mu': 0.0284, 'sigma': np.sqrt(0.001**2 + 0.0056**2)},  # From TS3 Tom Wilson and script_prior
                                                  'category': 'normal',
                                                  'joint_prior_ref': None},
                                        'unit': 'wo unit',
                                        'value': None},
                             'contam': {'duplicate': 'LC_CHEOPS_inst0_contam',
                                        'free': False,
                                        'prior': {'args': {'vmax': 1.0, 'vmin': 0.0},
                                                  'category': 'uniform',
                                                  'joint_prior_ref': None},
                                        'unit': 'wo unit',
                                        'value': 0},
                             'jitter': {'duplicate': 'LC_CHEOPS_inst0_jitter',
                                        'free': True,
                                        'prior': {'args': {'vmax': 1.0, 'vmin': 0.0},
                                                  'category': 'uniform',
                                                  'joint_prior_ref': None},
                                        'unit': None,
                                        'value': None}},
                 'instTr4': {'DeltaF': {'duplicate': None,
                                        'free': True,
                                        'prior': {'args': {'mu': 0.0284, 'sigma': np.sqrt(0.001**2 + 0.0056**2)},  # From TS3 Tom Wilson and script_prior
                                                  'category': 'normal',
                                                  'joint_prior_ref': None},
                                        'unit': 'wo unit',
                                        'value': None},
                             'contam': {'duplicate': 'LC_CHEOPS_inst0_contam',
                                        'free': False,
                                        'prior': {'args': {'vmax': 1.0, 'vmin': 0.0},
                                                  'category': 'uniform',
                                                  'joint_prior_ref': None},
                                        'unit': 'wo unit',
                                        'value': 0},
                             'jitter': {'duplicate': 'LC_CHEOPS_inst0_jitter',
                                        'free': True,
                                        'prior': {'args': {'vmax': 1.0, 'vmin': 0.0},
                                                  'category': 'uniform',
                                                  'joint_prior_ref': None},
                                        'unit': None,
                                        'value': None}},
                 'instTr5': {'DeltaF': {'duplicate': None,
                                        'free': True,
                                        'prior': {'args': {'mu': 0.0284, 'sigma': np.sqrt(0.001**2 + 0.0059**2)},  # From TS3 Tom Wilson and script_prior
                                                  'category': 'normal',
                                                  'joint_prior_ref': None},
                                        'unit': 'wo unit',
                                        'value': None},
                             'contam': {'duplicate': 'LC_CHEOPS_inst0_contam',
                                        'free': False,
                                        'prior': {'args': {'vmax': 1.0, 'vmin': 0.0},
                                                  'category': 'uniform',
                                                  'joint_prior_ref': None},
                                        'unit': 'wo unit',
                                        'value': 0},
                             'jitter': {'duplicate': 'LC_CHEOPS_inst0_jitter',
                                        'free': True,
                                        'prior': {'args': {'vmax': 1.0, 'vmin': 0.0},
                                                  'category': 'uniform',
                                                  'joint_prior_ref': None},
                                        'unit': None,
                                        'value': None}}}}

# instruments IND-ROLL
INDROLL = {'CHEOPS': {'Dataset': {0: 'inst',
                                  1: 'inst',
                                  2: 'inst',
                                  10: 'inst',
                                  11: 'inst',
                                  12: 'inst',
                                  13: 'inst',
                                  14: 'inst',
                                  15: 'inst',
                                  100: 'inst',
                                  101: 'inst',
                                  102: 'inst',
                                  103: 'inst',
                                  104: 'inst',
                                  105: 'inst',
                                  106: 'inst',
                                  107: 'inst',
                                  108: 'inst',
                                  109: 'inst',
                                  110: 'inst',
                                  111: 'inst',
                                  112: 'inst',
                                  113: 'inst',
                                  114: 'inst',
                                  115: 'inst',
                                  116: 'inst',
                                  117: 'inst',
                                  118: 'inst',
                                  119: 'inst'},
                      'inst': {}}}

# instruments IND-CX
INDCX = {'CHEOPS': {'Dataset': {0: 'inst',
                                1: 'inst',
                                2: 'inst',
                                10: 'inst',
                                11: 'inst',
                                12: 'inst',
                                13: 'inst',
                                14: 'inst',
                                15: 'inst',
                                100: 'inst',
                                101: 'inst',
                                102: 'inst',
                                103: 'inst',
                                104: 'inst',
                                105: 'inst',
                                106: 'inst',
                                107: 'inst',
                                108: 'inst',
                                109: 'inst',
                                110: 'inst',
                                111: 'inst',
                                112: 'inst',
                                113: 'inst',
                                114: 'inst',
                                115: 'inst',
                                116: 'inst',
                                117: 'inst',
                                118: 'inst',
                                119: 'inst'},
                    'inst': {}}}

# instruments IND-CY
INDCY = {'CHEOPS': {'Dataset': {0: 'inst',
                                1: 'inst',
                                2: 'inst',
                                10: 'inst',
                                11: 'inst',
                                12: 'inst',
                                13: 'inst',
                                14: 'inst',
                                15: 'inst',
                                100: 'inst',
                                101: 'inst',
                                102: 'inst',
                                103: 'inst',
                                104: 'inst',
                                105: 'inst',
                                106: 'inst',
                                107: 'inst',
                                108: 'inst',
                                109: 'inst',
                                110: 'inst',
                                111: 'inst',
                                112: 'inst',
                                113: 'inst',
                                114: 'inst',
                                115: 'inst',
                                116: 'inst',
                                117: 'inst',
                                118: 'inst',
                                119: 'inst'},
                    'inst': {}}}

# instruments IND-SMEAR
INDSMEAR = {'CHEOPS': {'Dataset': {0: 'inst',
                                   1: 'inst',
                                   2: 'inst',
                                   10: 'inst',
                                   11: 'inst',
                                   12: 'inst',
                                   13: 'inst',
                                   14: 'inst',
                                   15: 'inst',
                                   100: 'inst',
                                   101: 'inst',
                                   102: 'inst',
                                   103: 'inst',
                                   104: 'inst',
                                   105: 'inst',
                                   106: 'inst',
                                   107: 'inst',
                                   108: 'inst',
                                   109: 'inst',
                                   110: 'inst',
                                   111: 'inst',
                                   112: 'inst',
                                   113: 'inst',
                                   114: 'inst',
                                   115: 'inst',
                                   116: 'inst',
                                   117: 'inst',
                                   118: 'inst',
                                   119: 'inst'},
                       'inst': {}}}

# instruments IND-TF
INDTF = {'CHEOPS': {'Dataset': {0: 'inst',
                                1: 'inst',
                                2: 'inst',
                                10: 'inst',
                                11: 'inst',
                                12: 'inst',
                                13: 'inst',
                                14: 'inst',
                                15: 'inst',
                                100: 'inst',
                                101: 'inst',
                                102: 'inst',
                                103: 'inst',
                                104: 'inst',
                                105: 'inst',
                                106: 'inst',
                                107: 'inst',
                                108: 'inst',
                                109: 'inst',
                                110: 'inst',
                                111: 'inst',
                                112: 'inst',
                                113: 'inst',
                                114: 'inst',
                                115: 'inst',
                                116: 'inst',
                                117: 'inst',
                                118: 'inst',
                                119: 'inst'},
                    'inst': {}}}

# instruments IND-BKG
INDBKG = {'CHEOPS': {'Dataset': {0: 'inst',
                                 1: 'inst',
                                 2: 'inst',
                                 10: 'inst',
                                 11: 'inst',
                                 12: 'inst',
                                 13: 'inst',
                                 14: 'inst',
                                 15: 'inst',
                                 100: 'inst',
                                 101: 'inst',
                                 102: 'inst',
                                 103: 'inst',
                                 104: 'inst',
                                 105: 'inst',
                                 106: 'inst',
                                 107: 'inst',
                                 108: 'inst',
                                 109: 'inst',
                                 110: 'inst',
                                 111: 'inst',
                                 112: 'inst',
                                 113: 'inst',
                                 114: 'inst',
                                 115: 'inst',
                                 116: 'inst',
                                 117: 'inst',
                                 118: 'inst',
                                 119: 'inst'},
                     'inst': {}}}

# instruments IND-DARK
INDDARK = {'CHEOPS': {'Dataset': {0: 'inst',
                                  1: 'inst',
                                  2: 'inst',
                                  10: 'inst',
                                  11: 'inst',
                                  12: 'inst',
                                  13: 'inst',
                                  14: 'inst',
                                  15: 'inst',
                                  100: 'inst',
                                  101: 'inst',
                                  102: 'inst',
                                  103: 'inst',
                                  104: 'inst',
                                  105: 'inst',
                                  106: 'inst',
                                  107: 'inst',
                                  108: 'inst',
                                  109: 'inst',
                                  110: 'inst',
                                  111: 'inst',
                                  112: 'inst',
                                  113: 'inst',
                                  114: 'inst',
                                  115: 'inst',
                                  116: 'inst',
                                  117: 'inst',
                                  118: 'inst',
                                  119: 'inst'},
                      'inst': {}}}

# instruments IND-CONTA
INDCONTA = {'CHEOPS': {'Dataset': {0: 'inst',
                                   1: 'inst',
                                   2: 'inst',
                                   10: 'inst',
                                   11: 'inst',
                                   12: 'inst',
                                   13: 'inst',
                                   14: 'inst',
                                   15: 'inst',
                                   100: 'inst',
                                   101: 'inst',
                                   102: 'inst',
                                   103: 'inst',
                                   104: 'inst',
                                   105: 'inst',
                                   106: 'inst',
                                   107: 'inst',
                                   108: 'inst',
                                   109: 'inst',
                                   110: 'inst',
                                   111: 'inst',
                                   112: 'inst',
                                   113: 'inst',
                                   114: 'inst',
                                   115: 'inst',
                                   116: 'inst',
                                   117: 'inst',
                                   118: 'inst',
                                   119: 'inst'},
                       'inst': {}}}
# stars
A = {'rho': {'duplicate': None,
             'free': True,
             'prior': {'args': {'mu': 0.2299499918941955, 'sigma': 0.015254611012997882, 'lims': [0, np.inf]},  # from TS3 M and R estimate (https://docs.google.com/spreadsheets/d/12KA3-A3h5T7IJR5J7T1DE9SYTtjoS8rI6-98HwgQFF4/edit#gid=1232635509)
                       'category': 'normal',
                       'joint_prior_ref': None},
             'unit': None,
             'value': None}}


# planets
b = {'A': {'duplicate': None,
           'free': True,
           'prior': {'args': {'vmin': 0.0, 'vmax': 1e-3},  # Arbitrary
                     'category': 'uniform',
                     'joint_prior_ref': None},
           'unit': None,
           'value': None},
     'Foffset': {'duplicate': None,
                 'free': True,
                 'prior': {'args': {'vmin': 0.0, 'vmax': 1e-3},  # Arbitrary
                           'category': 'uniform',
                           'joint_prior_ref': None},
                 'unit': None,
                 'value': None},
     'P': {'duplicate': None,
           'free': True,
           'prior': {'args': {'mu': 1.80988198, 'sigma': 0.00000060, 'lims': [0, np.inf]},  # From TEPCat (https://www.astro.keele.ac.uk/jkt/tepcat/planets/WASP-076.html) and at the time Ehrenreich+2020 (https://arxiv.org/pdf/2003.05528.pdf)
                     'category': 'normal',
                     'joint_prior_ref': None},
           'unit': None,
           'value': None},
     'Phi': {'duplicate': None,
             'free': True,
             'prior': {'args': {'vmin': np.pi / 2, 'vmax': 3 * np.pi / 2},
                       'category': 'uniform',
                       'joint_prior_ref': None},
             'unit': None,
             'value': None},
     'Rrat': {'duplicate': None,
              'free': True,
              'prior': {'args': {'mu': 0.10852, 'sigma': 0.10852 * 0.20},  # 0.10852 +0.00096 -0.00072 From Ehrenreich+2020: https://arxiv.org/pdf/2003.05528.pdf
                        'category': 'normal',
                        'joint_prior_ref': None},
              'unit': None,
              'value': None},
     'cosinc': {'duplicate': None,
                'free': True,
                'prior': {'args': {'mu': 0.0065828112238361, 'sigma': 0.0005920112790993829, 'lims': [0, 1]},  # From Ehrenreich+2020: https://arxiv.org/pdf/2003.05528.pdf
                          'category': 'normal',
                          'joint_prior_ref': None},
                'unit': 'w/o unit',
                'value': None},
     'ecosw': {'duplicate': None,
               'free': True,
               'prior': {'args': {'vmax': 1.0, 'vmin': 0.0},
                         'category': 'uniform',
                         'joint_prior_ref': 'polarew'},
               'unit': 'w/o unit',
               'value': None},
     'esinw': {'duplicate': None,
               'free': True,
               'prior': {'args': {'vmax': 1.0, 'vmin': 0.0},
                         'category': 'uniform',
                         'joint_prior_ref': 'polarew'},
               'unit': 'w/o unit',
               'value': None},
     'tic': {'duplicate': None,
             'free': True,
             'prior': {'args': {'mu': 1080.62617, 'sigma': 0.00040},  # 2458080.62617 ± 0.00040 - 2457000 From Ehrenreich+2020: https://arxiv.org/pdf/2003.05528.pdf
                       'category': 'normal',
                       'joint_prior_ref': None},
             'unit': None,
             'value': None}}


# LDs
A_LD = {'ldc1': {'duplicate': None,
                 'free': True,
                 'prior': {'args': {'mu': 0.0375, 'sigma': 0.0078},  # LDTk from TS3 inputs
                           'category': 'normal',
                           'joint_prior_ref': None},
                 'unit': None,
                 'value': None},
        'ldc2': {'duplicate': None,
                 'free': True,
                 'prior': {'args': {'mu': 0.8102, 'sigma': 0.0087},  # LDTk from TS3 inputs
                           'category': 'normal',
                           'joint_prior_ref': None},
                 'unit': None,
                 'value': None},
        'ldc3': {'duplicate': None,
                 'free': True,
                 'prior': {'args': {'mu': -0.1034, 'sigma': 0.0089},  # LDTk from TS3 inputs
                           'category': 'normal',
                           'joint_prior_ref': None},
                 'unit': None,
                 'value': None},
        'ldc4': {'duplicate': None,
                 'free': True,
                 'prior': {'args': {'mu': -0.0926, 'sigma': 0.0051},  # LDTk from TS3 inputs
                           'category': 'normal',
                           'joint_prior_ref': None},
                 'unit': None,
                 'value': None}}

# GravitionalGroups

WASP76 = {}

# Joint parameters
# Define below the joint parameter distributions.
joint_prior = {'polarew': {'category': 'polar', 'args': {'r_prior': {'category': 'uniform', 'args': {'vmin': 0.0, 'vmax': 0.1}},
                                                         'theta_prior': {'category': 'uniform', 'args': {'vmin': -np.pi, 'vmax': np.pi}},
                                                         },
                           'params': {'x': 'WASP-76_b_ecosw', 'y': 'WASP-76_b_esinw'}
                           },
               }
