name: lisa
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - ipython
  - numpy
  - scipy
  - matplotlib
  - emcee
  - astropy
  - corner
  - dill
  - george
  - tqdm
  - statsmodels
  - pandas
  - python-dateutil
  - loguru
  - arviz
  - pip
  - pip:
    - radvel
    - celerite2
    - kelp
    - PyAstronomy[occult]

variables:
  LISAPATH: /Users/olivier/Softwares/lisa
  LISADEVPATH: /Users/olivier/Softwares/lisa-dev
