name: lisa
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.11
  - numpy
  - scipy
  - matplotlib
  - krb5
  - libcurl
  - h5py
  - emcee
  - astropy
  - corner
  - dill
  - george
  - tqdm
  - statsmodels
  - pandas
  - loguru
  - arviz
  - jax
  - uncertainties
  - ipython
  - ipympl
  - mkdocs
  - mkdocs-material
  - ruff 
  - mypy 
  - pytest
  - pip
  - pip:
      - -e .
      - radvel
      - celerite2
      - git+https://github.com/bmorris3/kelp.git
      - PyAstronomy
      - batman-package
      - pytransit
      - ldtk
      - types-tqdm
