name: lisa
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - ipython
  - numpy
  - scipy
  - matplotlib
  - emcee
  - astropy
  - corner
  - dill
  - george
  - tqdm
  - statsmodels
  - pandas
  - loguru
  - arviz
  - jax
  - uncertainties
  - ipympl  # For jupyter notebook backend
  - pip
  - pip:
    - radvel
    - celerite2
    - git+https://github.com/bmorris3/kelp.git
    - PyAstronomy
    - batman-package
    - pytransit
    - ldtk

variables:
  LISAPATH: /Users/olivier/Softwares/lisa