#!/usr/bin/python
# -*- coding:  utf-8 -*-
# Model parametrisation file of WASP-76
# Parameters

# Orbital models
orbital_model = {'b': {'do': True,
                       'model4instrument': {'LC_CHEOPS_inst0': '0',
                                            'LC_CHEOPS_inst1': '1',
                                            'LC_CHEOPS_inst2': '2',
                                            'LC_CHEOPS_inst3': '3',
                                            'LC_CHEOPS_inst4': '4'},
                       'model_definitions': {'0': {'category': 'batman',
                                                   'param_extensions': {'planet': {'P': '',
                                                                                   'cosinc': '',
                                                                                   'ecosw': '',
                                                                                   'esinw': '',
                                                                                   'tic': '0'},
                                                                        'star': {'rho': ''}},
                                                   'parametrisation': {'ew_format': 'ecosw-esinw',
                                                                       'inc_format': 'cosinc',
                                                                       'use_aR': False,
                                                                       'use_tic': True}
                                                   },
                                             '1': {'category': 'batman',
                                                   'param_extensions': {'planet': {'P': '',
                                                                                   'cosinc': '',
                                                                                   'ecosw': '',
                                                                                   'esinw': '',
                                                                                   'tic': '1'},
                                                                        'star': {'rho': ''}},
                                                   'parametrisation': {'ew_format': 'ecosw-esinw',
                                                                       'inc_format': 'cosinc',
                                                                       'use_aR': False,
                                                                       'use_tic': True}
                                                   },
                                             '2': {'category': 'batman',
                                                   'param_extensions': {'planet': {'P': '',
                                                                                   'cosinc': '',
                                                                                   'ecosw': '',
                                                                                   'esinw': '',
                                                                                   'tic': '2'},
                                                                        'star': {'rho': ''}},
                                                   'parametrisation': {'ew_format': 'ecosw-esinw',
                                                                       'inc_format': 'cosinc',
                                                                       'use_aR': False,
                                                                       'use_tic': True}
                                                   },
                                             '3': {'category': 'batman',
                                                   'param_extensions': {'planet': {'P': '',
                                                                                   'cosinc': '',
                                                                                   'ecosw': '',
                                                                                   'esinw': '',
                                                                                   'tic': '3'},
                                                                        'star': {'rho': ''}},
                                                   'parametrisation': {'ew_format': 'ecosw-esinw',
                                                                       'inc_format': 'cosinc',
                                                                       'use_aR': False,
                                                                       'use_tic': True}
                                                   },
                                             '4': {'category': 'batman',
                                                   'param_extensions': {'planet': {'P': '',
                                                                                   'cosinc': '',
                                                                                   'ecosw': '',
                                                                                   'esinw': '',
                                                                                   'tic': '4'},
                                                                        'star': {'rho': ''}},
                                                   'parametrisation': {'ew_format': 'ecosw-esinw',
                                                                       'inc_format': 'cosinc',
                                                                       'use_aR': False,
                                                                       'use_tic': True}
                                                   },
                                             }}}
